baseURL = 'https://systemsthatserve.github.io/'
languageCode = 'en-us'
title = 'Systems That Serve'
theme = "not-much"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3

[params]
  showThemeNotice = true